### PR TITLE
adding test perameters

### PR DESCRIPTION
**Pull request by TaylahB**
Adding parameters to the __main__.py file such that testing may occur

### CODE REVIEW

**Comment by YourLocalBlake** [comment]
bors try

**Comment by YourLocalBlake** [comment]
There are still several typos I have fixed in a local version. Additionally it is looking for a sky_lines.dat file which I'm investigating

**Comment by aragilar** [comment]
Ah, cool

**Comment by YourLocalBlake** [comment]
Issue resolved in #57.

**Pull request closed without merging**
